# Generated by Django 4.0.4 on 2022-05-15 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyresponse_date_submited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user',
            new_name='owner',
        ),
    ]
